from django.urls import re_path, path
from . import views
app_name = 'users'
urlpatterns = [
    re_path(r'^new_goods/$', views.new_goods, name='new_goods'),#用户新建订单
    re_path(r'^edit_goods/$', views.edit_goods, name='edit_goods'),#显示专属快递员的专属订单
    re_path(r'^get_sign_list/$', views.get_sign_list, name='get_sign_list'),#用户获得待签收订单列表
    re_path(r'^zh_xie_goods/$', views.zh_xie_goods, name='zh_xie_goods'),#司机查看装卸快递
    re_path(r'^fa_che/$', views.fa_che, name='fa_che'),
    re_path(r'^hui_cheng/$', views.hui_cheng, name='hui_cheng'),
    re_path(r'^zh_xie_goods_done/$', views.zh_xie_goods_done, name='zh_xie_goods_done'),#真正装卸
    re_path(r'^init_wares/$', views.init_wares, name='init_wares'),#初始化仓库
    re_path(r'^pay_wage/$', views.pay_wage, name='pay_wage'),#发工资
    re_path(r'^init_cars/$', views.init_cars, name='init_cars'),#初始化车辆
    re_path(r'^ru_ku_goods/$', views.ru_ku_goods, name='ru_ku_goods'),#显示快递员揽收之后入库订单
    re_path(r'^ru_ku_p_goods/$', views.ru_ku_p_goods, name='ru_ku_p_goods'),#显示快递派送未入库快递
    re_path(r'^ru_ku_p_o/$', views.ru_ku_p_o, name='ru_ku_p_o'),#入库派送订单
    re_path(r'^chu_ku_p_goods/$', views.chu_ku_p_goods, name='chu_ku_p_goods'),#显示快递派送未出库快递
    re_path(r'^chu_ku_p_done_goods/$', views.chu_ku_p_done_goods, name='chu_ku_p_done_goods'),#出库派送订单
    re_path(r'^p_goods/$', views.p_goods, name='p_goods'),#显示待派送快递
    re_path(r'^view_wage/$', views.view_wage, name='view_wage'),#显示工资view_cars
    re_path(r'^view_cars/$', views.view_cars, name='view_cars'),
    re_path(r'^cal_monthly/$', views.cal_monthly, name='cal_monthly'),#显示工资
    re_path(r'^view_all_price/$', views.view_all_price, name='view_all_price'),#获取未分配订单
    re_path(r'^p_done_goods/$', views.p_done_goods, name='p_done_goods'),#快递员签收派送订单
    re_path(r'^user_p_done_goods/$', views.user_p_done_goods, name='user_p_done_goods'),#用户签收派送订单
    re_path(r'^chu_ku_goods/$', views.chu_ku_goods, name='chu_ku_goods'),#显示快递员揽收之后出库订单
    re_path(r'^ru_ku_done_goods/$', views.ru_ku_done_goods, name='ru_ku_done_goods'),#真正入库揽收订单
    re_path(r'^chu_ku_done_goods/$', views.chu_ku_done_goods, name='chu_ku_done_goods'),#真正出库揽收订单
    re_path(r'^fen_pei/$', views.fen_pei, name='fen_pei'),#获取未分配订单
    re_path(r'^get_goods/$', views.goods_list, name='goods_list'),#获取未完成订单列表
    re_path(r'^get_cancel_list/$', views.is_cancel, name='get_cancel_list'),#查看已取消订单
    re_path(r'^fin_goods_list/$', views.fin_goods_list, name='fin_goods_list'),#用户查看已完成订单
    re_path(r'^get_prices/$', views.get_prices, name='get_prices'),#计算订单金额
    re_path(r'^cancerorder/$', views.cancerorder,  name='cancerorder'),#普通用户寄件取消
    re_path(r'^fen_pei_courier/$', views.fen_pei_courier,  name='fen_pei_courier'),#调度员分配快递员
    re_path(r'^judge/$', views.judge,  name='judge'),#用户添加评论
    re_path(r'^fin/$', views.fin,  name='fin'),
    re_path(r'^user/(?P<pk>\d+)/profile/$', views.profile, name='profile'),
    re_path(r'^user/profile/(?P<pk>\d+)/s.html/$',views.review_create,  name='review_create'),
    re_path(r'^user/profile/courier/$',views.courier,  name='courier'),#快递员中心
    re_path(r'^user/profile/couriers/$',views.couriers,  name='couriers'),#会计财务中心
    re_path(r'^user/profile/cour/$',views.cour,  name='cour'),#调度员中心
    re_path(r'^user/profile/cars/$',views.cars,  name='cars'),#司机中心
    re_path(r'^user/profile/kuai/$',views.kuai,  name='kuai'),#调度员中心
    re_path(r'^user/profile/account.html/$',views.new_account,  name='new_account'),
    re_path(r'^register/$', views.register, name='register'),#注册用户
    re_path(r'^login/$', views.login, name='login'),#登录用户
    re_path(r'^user/(?P<pk>\d+)/profile/update/$', views.profile_update, name='profile_update'),#更改用户信息
    re_path(r'^user/(?P<pk>\d+)/pwdchange/$', views.pwd_change, name='pwd_change'),#更改用户密码
    re_path(r'^logout/$', views.logout, name='logout'),#用户登出
    re_path(r'^loginn/$',views.login_view, name='loginn'),
    re_path(r'^logoutt/$', views.logout_view, name='logoutt'),
    re_path(r'^img_captcha/$',views.img_captcha, name='img_captcha'),
    re_path(r'^sms_captcha/$',views.sms_captcha, name='sms_captcha'),
    re_path(r'^registerr/$',views.log_register, name='registerr'),
    re_path(r'^cache/$',views.cache_test, name='cache'),
    re_path(r'^list/$', views.goods_list, name='good_list'),
]