# Generated by Django 2.1.7 on 2019-05-23 04:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=20)),
                ('capacity', models.IntegerField(blank=True, default=1000)),
                ('chu', models.CharField(blank=True, max_length=20)),
                ('di', models.CharField(blank=True, max_length=20)),
                ('real', models.CharField(blank=True, max_length=20)),
                ('cc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeliverReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five')], default=1, verbose_name='Rating (stars)')),
                ('comment', models.TextField(blank=True, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(max_length=32)),
                ('rname', models.CharField(max_length=32)),
                ('stel', models.CharField(max_length=11)),
                ('scity', models.CharField(max_length=10)),
                ('saddress', models.CharField(max_length=11)),
                ('rtel', models.CharField(max_length=11)),
                ('gweight', models.FloatField()),
                ('gdest', models.CharField(max_length=20)),
                ('detail', models.CharField(max_length=30)),
                ('is_active', models.BooleanField()),
                ('is_cancel', models.BooleanField()),
                ('status', models.IntegerField(blank=True)),
                ('judge', models.CharField(blank=True, max_length=100)),
                ('cname', models.CharField(blank=True, max_length=20)),
                ('oname', models.CharField(blank=True, max_length=20)),
                ('cs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prices', models.FloatField()),
                ('ps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Goods')),
            ],
        ),
        migrations.CreateModel(
            name='Trans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_re', models.BooleanField()),
                ('is_rukush', models.BooleanField()),
                ('is_chukush', models.BooleanField()),
                ('is_chufa', models.BooleanField()),
                ('daona', models.CharField(blank=True, max_length=20)),
                ('is_rukuqita', models.BooleanField()),
                ('is_chukuqita', models.BooleanField()),
                ('is_sign', models.BooleanField()),
                ('gs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Goods')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org', models.CharField(blank=True, max_length=128, verbose_name='Organization')),
                ('org_id', models.CharField(blank=True, max_length=5, verbose_name='Org_id')),
                ('telephone', models.CharField(blank=True, max_length=50, verbose_name='Telephone')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='Last modified')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
            },
        ),
        migrations.CreateModel(
            name='Wage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wage', models.FloatField(blank=True)),
                ('ps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wname', models.CharField(blank=True, max_length=10)),
                ('capacity', models.IntegerField(blank=True, default=1000)),
                ('restroom', models.IntegerField(blank=True)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('ws', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='deliverreview',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliver_reviews', to='users.Goods'),
        ),
        migrations.AddField(
            model_name='deliverreview',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Goods'),
        ),
    ]
